"""add user_impact_event

Revision ID: 2a8c0d3e1f4b
Revises: 05b2f0c2b510
Create Date: 2025-10-22 03:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8c0d3e1f4b'
down_revision = '05b2f0c2b510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_impact_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('item_category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('weight_diverted_kg', sa.Float(), nullable=False),
    sa.Column('money_saved_kes', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_impact_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_impact_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_impact_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_impact_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_impact_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_impact_events_event_type'))

    op.drop_table('user_impact_events')
    # ### end Alembic commands ###
